---
MD003:
  style: atx
MD004:
  style: dash
MD009: false
MD012:
  maximum: 1
MD013: false
MD024:
  siblings_only: true
MD027: false
MD029: false
MD031: false
MD032: false
MD033:
  allowed_elements:
    - a
    - abbr
    - br
    - caption
    - code
    - dd
    - del
    - details
    - dl
    - dt
    - em
    - figcaption
    - figure
    - img
    - kbd
    - li
    - mark
    - picture
    - source
    - strong
    - summary
    - sup
    - table
    - tbody
    - td
    - tfoot
    - th
    - thead
    - tr
    - ul
    - video
MD034: false
MD041: false
MD049: false
MD051: false
MD060: false
# Autoformatter friendly markdownlint config with a narrow inline-HTML allowlist
default: true
